include: package:flutter_lints/flutter.yaml

linter:
  rules:
    # Prefer to use type-safe collection literals for `Map` and `List`.
    # Good: `const <String, int>{}`
    # Bad: `const {}`
    avoid_empty_else: true
    avoid_unnecessary_containers: true
    avoid_print: true
    sort_child_properties_last: true
    prefer_const_constructors: true
    prefer_const_declarations: true
    prefer_const_literals_to_create_immutables: true
    prefer_if_null_operators: true
    prefer_final_fields: true
    prefer_single_quotes: true
    require_trailing_commas: true
    sized_box_for_whitespace: true
    use_key_in_widget_constructors: true
    unnecessary_brace_in_string_interps: true

# Additional information about this file can be found at
# https://dart.dev/guides/language/analysis-options 